### ISSUE TITLE
Pt-Br pages

### ISSUE THREAD

**Issue by Gustavo1801** [PinguinoIDE/pinguinoide.github.io#20]
the links on the pages pt-br are not working, they always go to 404

**Comment by luzemario** [comment]
The links are broken, but you can select pt-br again on some pages. The content can be displayed in Brazilian Portuguese. However, the download page is available in english right now. We are working in it.

@MefhigosetH Can you correct the links on the main page?

**Comment by MefhigosetH** [comment]
Hi there!

Yes @luzemario , I can fix this this weekend.

Thanks for the feedback.
